# Generated by Django 5.1.7 on 2025-05-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nit', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='NIT')),
                ('name', models.CharField(max_length=100, verbose_name='nombre de la empresa')),
                ('address', models.TextField(verbose_name='dirección de la empresa')),
                ('phone', models.CharField(max_length=20, verbose_name='telefono de la empresa')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre del producto')),
                ('features', models.TextField(verbose_name='caracteristicas')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='COP', max_length=3, verbose_name='moneda')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='company.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'precio del producto',
                'verbose_name_plural': 'precios de los productos',
            },
        ),
    ]
